import {
  AlertCircle,
  AlertTriangle,
  Circle,
  PlusCircle,
  RefreshCw,
} from 'lucide-react';
import {
  CheckboxSharp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsVertical,
  ChevronUp,
  Eye,
  EyeOff,
  KeyboardMusicSharp,
  Lightbulb,
  LockSharp,
  MailSharp,
  Menu,
  Moon,
  MoreHorizontalSharp,
  Plus,
  PlusBoxSharp,
  Search,
  SettingsCog2,
  SquareAlertSharp,
  UploadSharp,
  UserSharp,
} from 'pixelarticons/react';

const XIcon = () => <span>✕</span>;

export const Icons = {
  Lightbulb,
  Moon,
  Eye,
  EyeOff,
  LockSharp,
  UserSharp,
  SettingsCog: SettingsCog2,
  KeyboardMusicSharp,
  ChevronUp,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronsVertical,
  SquareAlertSharp,
  UploadSharp,
  Menu,
  RefreshCw,
  CheckboxSharp,
  PlusBoxSharp,
  MoreHorizontalSharp,
  Search,
  XIcon,
  Circle,
  Plus,
  MailSharp,
  AlertCircle,
  AlertTriangle,
  PlusCircle,
};
